name: Deploy Node.js App (from /client) to Azure (Windows)

on:
  push:
    branches:
      - main  # Adjust this if your deployment branch differs

jobs:
  build-and-deploy:
    runs-on: windows-latest  # Important: App Service uses Windows

    defaults:
      run:
        working-directory: ./client  # Set working directory for all steps

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Build frontend
      run: npm run build  # Ensure your build outputs to /client/build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: agrinexus-hgh6e4aff6hhepdz
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./client
