name: Build and deploy Node.js client app to Azure Web App - agrinexus

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        working-directory: ./client
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-app
          path: ./client  # 👈 the built project to deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: client-app

      # Option 1: Using Azure CLI with device code login (manual interaction)
      - name: Set up Azure CLI
        uses: azure/setup-azcli@v1

      - name: Azure CLI login (device code authentication)
        run: |
          az login --use-device-code  # This will prompt for manual login

      # OR Option 2: Using Azure Service Principal (if you want to use secrets)
      # Uncomment the following section if you prefer using the Azure Service Principal:
      # - name: Azure Login (using Service Principal credentials)
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'agrinexus'  # 👈 your Azure Web App name
          slot-name: 'Production'
          package: ./client  # Path to the built project you want to deploy

      # Optional: Output Web App URL
      - name: Output web app URL
        run: echo "Web app URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
