name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to windows-latest for Windows builds

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # Set the Node.js version you need

      # Install dependencies and build the app
      - name: Install Dependencies
        run: |
          npm install

      - name: Build Application
        run: |
          npm run build  # Adjust this command based on your build script

      # Upload build artifacts (optional if you want to store them for later use)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-app
          path: ./client  # Adjust the path to where your build files are located

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deployment happens after the build job
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download build artifacts if you uploaded them in the previous step
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: client-app

      # Azure Login: Use GitHub's built-in OAuth authentication to connect to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          # No need to manually pass client-id, tenant-id, or subscription-id
          token: ${{ secrets.GITHUB_TOKEN }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}  # Azure Web App name stored as GitHub secret
          slot-name: 'Production'  # Or the slot you're using
          package: ./client  # Path to your build output directory

