name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Running on Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Install dependencies (adjust for the subdirectory with package.json)
      - name: Install Dependencies
        working-directory: .\client  # Specify the subdirectory if package.json is inside 'client/'
        run: |
          npm install

      # Build the application (adjust for the subdirectory with the build files)
      - name: Build Application
        working-directory: .\client  # Specify the correct path to your build files
        run: |
          npm run build

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-app
          path: .\client  # Adjust the path to where your build files are located

  deploy:
    runs-on: windows-latest
    needs: build  # Ensure deployment happens after the build job
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download build artifacts if you uploaded them in the previous step
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: client-app

      # Azure Login: Use GitHub's built-in OAuth authentication (no need to pass client-id, tenant-id, or subscription-id)
      - name: Azure Login
        uses: azure/login@v2
        with:
          # No need to pass 'token', instead, GitHub automatically handles the authentication.
          # Use the default authentication method (OAuth)
          auth-type: 'OAuth'  # Using GitHub OAuth to authenticate
          enable-AzPSSession: true

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}  # Azure Web App name stored as GitHub secret
          slot-name: 'Production'  # Or specify a slot name
          package: .\client  # Path to your built application

